import type { Metadata } from "next";
import { Inter } from "next/font/google";
import clsx from "clsx";
import { MainProvider } from "@/src/providers/MainProvider";
import Header from "@/src/components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(inter.className)}>
        <div id="__next">
          <MainProvider>
            <Header />
            <main className="bg-gradient-to-br from-indigo-500 via-purple-500 to-pink-500">
              {children}
            </main>
          </MainProvider>
        </div>
      </body>
    </html>
  );
}
